# Generated by Django 3.2.25 on 2025-12-01 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('ID_area', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre_area', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Áreas',
            },
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('ID_cargo', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre_cargo', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Cargos',
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('ID_estado', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre_estado', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('Rut', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=100)),
                ('Apellido', models.CharField(max_length=100)),
                ('Telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('Email', models.EmailField(blank=True, max_length=100, null=True)),
                ('ID_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turnos.area', verbose_name='Área')),
                ('ID_cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turnos.cargo', verbose_name='Cargo')),
            ],
            options={
                'verbose_name_plural': 'Personas',
            },
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('ID_turno', models.AutoField(primary_key=True, serialize=False)),
                ('Tipo_turno', models.CharField(max_length=100)),
                ('Hora_inicio', models.TimeField()),
                ('Hora_fin', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='RegistroTurno',
            fields=[
                ('ID_registro', models.AutoField(primary_key=True, serialize=False)),
                ('Fecha', models.DateField()),
                ('Hora_llegada_real', models.TimeField(blank=True, null=True)),
                ('Minutos_tardanza', models.IntegerField(blank=True, null=True)),
                ('ID_estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turnos.estado', verbose_name='Estado de Asistencia')),
                ('ID_turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turnos.turno', verbose_name='Turno Programado')),
                ('Rut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turnos.persona', verbose_name='Bombero')),
            ],
            options={
                'verbose_name_plural': 'Registros de Turnos',
            },
        ),
    ]
