# Generated by Django 3.2.25 on 2025-12-06 17:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('ID_area', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre_area', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'area',
            },
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('ID_cargo', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre_cargo', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'cargo',
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('ID_estado', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre_estado', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'estado',
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('Rut', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=50)),
                ('Apellido', models.CharField(max_length=50)),
                ('Telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('Email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('Fecha_ingreso', models.DateField()),
                ('ID_area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='turnos.area')),
                ('ID_cargo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='turnos.cargo')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='persona', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'persona',
            },
        ),
        migrations.CreateModel(
            name='RegistroTurno',
            fields=[
                ('ID_registro', models.AutoField(primary_key=True, serialize=False)),
                ('Fecha', models.DateField()),
                ('Hora_llegada_real', models.TimeField(blank=True, null=True)),
                ('Minutos_tardanza', models.IntegerField(default=0)),
                ('ID_estado', models.ForeignKey(db_column='ID_estado_id', on_delete=django.db.models.deletion.PROTECT, to='turnos.estado')),
            ],
            options={
                'db_table': 'registro_turno',
            },
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('ID_turno', models.AutoField(primary_key=True, serialize=False)),
                ('Tipo_turno', models.CharField(max_length=50)),
                ('Hora_inicio', models.TimeField()),
                ('Hora_fin', models.TimeField()),
                ('Duracion_horas', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
            options={
                'db_table': 'turnos_turno',
            },
        ),
        migrations.CreateModel(
            name='SolicitudCambio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon', models.TextField(verbose_name='Razón de la solicitud')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aceptada', 'Aceptada'), ('Rechazada', 'Rechazada')], default='Pendiente', max_length=10)),
                ('autorizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_procesadas', to=settings.AUTH_USER_MODEL)),
                ('persona_solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_enviadas', to='turnos.persona')),
                ('registro_turno', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_de_cambio', to='turnos.registroturno')),
            ],
            options={
                'db_table': 'turnos_solicitudcambio',
            },
        ),
        migrations.AddField(
            model_name='registroturno',
            name='ID_turno',
            field=models.ForeignKey(db_column='ID_turno_id', on_delete=django.db.models.deletion.PROTECT, to='turnos.turno'),
        ),
        migrations.AddField(
            model_name='registroturno',
            name='Rut',
            field=models.ForeignKey(db_column='Rut_id', on_delete=django.db.models.deletion.PROTECT, to='turnos.persona'),
        ),
        migrations.AlterUniqueTogether(
            name='registroturno',
            unique_together={('Rut', 'Fecha')},
        ),
    ]
