# Generated by Django 3.2.25 on 2025-12-06 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroturno',
            name='ID_turno',
            field=models.ForeignKey(db_column='ID_turno_id', on_delete=django.db.models.deletion.CASCADE, to='turnos.turno'),
        ),
        migrations.AlterField(
            model_name='turno',
            name='Duracion_horas',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
    ]
