# Generated by Django 3.2.25 on 2025-12-01 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='area',
            table='area',
        ),
        migrations.AlterModelTable(
            name='cargo',
            table='cargo',
        ),
        migrations.AlterModelTable(
            name='persona',
            table='persona',
        ),
        migrations.AlterModelTable(
            name='registroturno',
            table='registro_turno',
        ),
    ]
