# Generated by Django 3.2.25 on 2025-12-01 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0002_auto_20251201_0323'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estado',
            options={'verbose_name_plural': 'Estados'},
        ),
        migrations.AlterField(
            model_name='persona',
            name='ID_area',
            field=models.ForeignKey(db_column='ID_area', on_delete=django.db.models.deletion.CASCADE, to='turnos.area', verbose_name='Área'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='ID_cargo',
            field=models.ForeignKey(db_column='ID_cargo', on_delete=django.db.models.deletion.CASCADE, to='turnos.cargo', verbose_name='Cargo'),
        ),
        migrations.AlterField(
            model_name='registroturno',
            name='ID_estado',
            field=models.ForeignKey(db_column='ID_estado', on_delete=django.db.models.deletion.CASCADE, to='turnos.estado', verbose_name='Estado de Asistencia'),
        ),
        migrations.AlterField(
            model_name='registroturno',
            name='ID_turno',
            field=models.ForeignKey(db_column='ID_turno', on_delete=django.db.models.deletion.CASCADE, to='turnos.turno', verbose_name='Turno Programado'),
        ),
        migrations.AlterField(
            model_name='registroturno',
            name='Rut',
            field=models.ForeignKey(db_column='Rut', on_delete=django.db.models.deletion.CASCADE, to='turnos.persona', verbose_name='Bombero'),
        ),
        migrations.AlterModelTable(
            name='estado',
            table='estado',
        ),
        migrations.AlterModelTable(
            name='turno',
            table='turno',
        ),
    ]
