# Generated by Django 3.2.25 on 2025-12-03 23:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('turnos', '0004_persona_usuario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estado',
            options={},
        ),
        migrations.AlterField(
            model_name='persona',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Cuenta de Usuario (Login)'),
        ),
        migrations.CreateModel(
            name='SolicitudCambio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon', models.TextField(help_text='Explica brevemente por qué necesitas el cambio de turno.', verbose_name='Razón de la Solicitud')),
                ('estado', models.CharField(choices=[('Pendiente', 'En Proceso'), ('Aceptada', 'Aceptada'), ('Rechazada', 'Rechazada')], default='Pendiente', max_length=10, verbose_name='Estado de la Solicitud')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('autorizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Autorizado por')),
                ('persona_solicitante', models.ForeignKey(db_column='Rut_Solicitante', on_delete=django.db.models.deletion.CASCADE, to='turnos.persona', verbose_name='Solicitante')),
                ('registro_turno', models.ForeignKey(help_text='Selecciona el turno programado que deseas modificar.', on_delete=django.db.models.deletion.CASCADE, to='turnos.registroturno', verbose_name='Turno a Cambiar')),
            ],
            options={
                'verbose_name_plural': 'Solicitudes de Cambio',
            },
        ),
    ]
