# Generated by Django 3.2.25 on 2025-12-04 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0005_auto_20251203_2001'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='persona',
            options={'verbose_name': 'Personal de Bomberos', 'verbose_name_plural': 'Personal de Bomberos'},
        ),
        migrations.AlterModelOptions(
            name='registroturno',
            options={'verbose_name': 'Asistencia Programada', 'verbose_name_plural': 'Asistencia Programada'},
        ),
        migrations.AlterModelOptions(
            name='solicitudcambio',
            options={'verbose_name': 'Flujo de Cambio', 'verbose_name_plural': 'Flujo de Cambio de Turno'},
        ),
        migrations.AlterModelOptions(
            name='turno',
            options={'verbose_name': 'Tipo de Horario Fijo', 'verbose_name_plural': 'Tipos de Horario Fijo'},
        ),
    ]
